class HomePageLocators:
    LOGIN_BUTTON = '// *[ @ id = "menu-item-1235"] / a'
    MENU_BAR = '#site-navigation > div > div.menu-primary-menu-container'
    GDPR = '#cookie-notice > div'
    BASKET = '#page > div.col-full-nav > div > ul > li > div > a'
    BASKET_EMPTY = '#page > div.col-full-nav > div > ul > li > div > a > span.shoptimizer-cart-icon > span'
    GDPR_ACCEPT = '#cn-accept-cookie'
    STORE_BUTTON = '#nav-menu-item-33588 > a'
    MENS_WATCHES = '#nav-menu-item-26396 > a > span'
    FILTER = 'a.mobile-filter:nth-child(3)'
    FILTER_PRODUCTS = '#woocommerce_price_filter-2 > form > div > div.price_slider_amount > button'
    SHOP_BUTTON = '#nav-menu-item-33588 > a'
